HomeCentreProject/Controllers/BookController.cs
using BookCentreProject.RepositoryPattern.Interface;
using Microsoft.AspNetCore.Mvc;
using BookCentreProject.Models;
using BookCentreProject.ViewModel;
using static System.Net.Mime.MediaTypeNames;

namespace BookCentreProject.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookLibrary bookLibrary;
        private readonly IWebHostEnvironment webHost;

        public BookController(IBookLibrary bookLibrary,IWebHostEnvironment webHost)
        {
            this.bookLibrary = bookLibrary;
            this.webHost = webHost;
        }
        public async Task<IActionResult> GetBooks()

        {
            var data = await bookLibrary.GetBooks();

            return View(data);
        }
        public async Task<IActionResult> AddBook()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBook(BookViewModel  model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadFile(model);
                Book book = new Book()
                {
                    Name = model.Name,
                    Author = model.Author,
                    Language = model.Language,
                    Price = model.Price,
                    Type = model.Type,
                    Photo = uniqueFileName
                };
                await bookLibrary.AddBook(book);
                if (book.BookId == 0)
                {
                    TempData["Error"] = "Create Failed";

                }
                else
                {
                    TempData["Success"] = "Create Successfully";

                }

                return RedirectToAction("GetBooks");

                
            }

            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }
            else
            {
                Book book = await bookLibrary.GetBookById(id);
                BookEditViewModel bookEditViewModel = new BookEditViewModel()
                {
                    Id=book.BookId,
                    Name=book.Name,
                    Author=book.Author,
                    Language=book.Language,
                    Price=book.Price,
                    Type=book.Type,
                    ExistingImage=book.Photo

                };
                if (book == null)
                {
                    return NotFound();
                }
                return View(bookEditViewModel);
            }


        }
        [HttpPost]
        public async Task<IActionResult> Edit(BookEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Book book = await bookLibrary.GetBookById(model.Id);
                book.Name = model.Name;
                book.Author = model.Author;
                book.Language = model.Language;
                book.Price = model.Price;
                book.Type = model.Type;
                if(model.Image != null)
                {
                    if(model.ExistingImage != null)
                    {
                        string filePath = Path.Combine(webHost.WebRootPath,"images",model.ExistingImage );
                        System.IO.File.Delete(filePath);
                    }
                    book.Photo = ProcessUploadFile(model);
                }
                await bookLibrary.UpdateBook(book);
                

                if (book.BookId == 0)
                {
                    TempData["Error"] = "Create Failed";

                }
                else
                {
                    TempData["Success"] = "Create Successfully";

                }

                return RedirectToAction("GetBooks");


            }

            return View();
        }

        private string ProcessUploadFile(BookViewModel model)
        {
            string uniqueFileName = null;
            if (model.Image != null)
            {
                string UploadFolder = Path.Combine(webHost.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                string FilePath = Path.Combine(UploadFolder, uniqueFileName);
                using(var fileStream= new FileStream(FilePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);

                }
                
            }

            return uniqueFileName;
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return BadRequest();

            }
            else
            {
                 bool status = await bookLibrary.DeleteBook(id);
                    if (status)
                    {
                        TempData["Success"] = "Delete Successfully";

                    }
                    else
                    {
                        TempData["Error"] = "Delete Failed";
                    }
                
                return RedirectToAction("GetBooks");
            }

        }

                

               
        public async Task<IActionResult> Details(int id)
        {
            Book book= await bookLibrary.GetBookById(id);



            return View(book);
        }
      




    }
}

HomeCentreProject/Controllers/UserController.cs
using BookCentreProject.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookCentreProject.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;

        public UserController( SignInManager<IdentityUser> signInManager,UserManager<IdentityUser> userManager ) 
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task <IActionResult> Login(LoginVM model)
        {
            if (ModelState.IsValid)
            {
               var result= await signInManager.PasswordSignInAsync(model.UserName,model.Password,model.RememberMe,false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Username or password");
                    return View(model);
                }

            }
            return View(model);
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterVM model)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = model.Email,
                    Email = model.Email
                };
                var result=await userManager.CreateAsync(user,model.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user,false);
                    return RedirectToAction("Index", "Home");
                }
                foreach(var err in result.Errors)
                {
                    ModelState.AddModelError("",err.Description);
                    return View(model);
                }

            }
            return View(model);
        }
        
            
        
        public async Task <IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index","Home");
        }
    }
}

HomeCentreProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookCentre</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookCentreProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">BookCentre</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                       
                    </ul>
                    <ul class="navbar-nav ">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Book" asp-action="GetBooks">BookList</a>

                            </li>
                           
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="User">

                                    <button type="submit" class="nav-link btn btn-dark py-2 text-white">Logout @User.Identity.Name</button>

                                </form>

                            </li>
                        }
                        else
                        {
                           
                            <li class="nav-item">
                                <a class="nav-link text-dark " >
                                    <span class="badge badge-info">(0)</span>
                                    <i class="bi bi-cart4"> </i>
                                   
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white btn btn-dark" asp-area="" asp-controller="User" asp-action="Login">LogIn</a>
                            </li>


                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <body>
        <div class="container">
            <main role="main" class="pb-3">

                @RenderBody()
            </main>

        </div>

    </body>
  

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2024 - BookCentre - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>